<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuario', 'doctrine');

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_usuario
 * @property string $nombre
 * @property string $email
 * @property date $fecha_alta
 * @property integer $esta_activo
 * @property string $password
 * 
 * @method integer getIdUsuario()   Returns the current record's "id_usuario" value
 * @method string  getNombre()      Returns the current record's "nombre" value
 * @method string  getEmail()       Returns the current record's "email" value
 * @method date    getFechaAlta()   Returns the current record's "fecha_alta" value
 * @method integer getEstaActivo()  Returns the current record's "esta_activo" value
 * @method string  getPassword()    Returns the current record's "password" value
 * @method Usuario setIdUsuario()   Sets the current record's "id_usuario" value
 * @method Usuario setNombre()      Sets the current record's "nombre" value
 * @method Usuario setEmail()       Sets the current record's "email" value
 * @method Usuario setFechaAlta()   Sets the current record's "fecha_alta" value
 * @method Usuario setEstaActivo()  Sets the current record's "esta_activo" value
 * @method Usuario setPassword()    Sets the current record's "password" value
 * 
 * @package    yodonoytodosganamos
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('email', 'string', 40, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 40,
             ));
        $this->hasColumn('fecha_alta', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('esta_activo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('password', 'string', 10, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}