<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/06/08 20:31:39

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=yodono',
  'username' => 'yodono',
  'password' => 'yodono',
  'name' => 'doctrine',
)),);
