<?php

/**
 * CategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Categoria');
    }//end getInstance

  public function getActivas(){

	return $this->createQuery('Categoria')->where('categoria.esta_activa=True')->execute();
}//creo esta funcion que me devuelve las categorias que estan activas
}