<?php

/**
 * UsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioTable extends Doctrine_Table
{   
    const LOGIN_NO_EXISTE = 0;
    const LOGIN_OK = 1 ;    
    
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Usuario');
    }
    
    public function getUsuarioById($id)
    {
	   return $this->createQuery('Usuario')
                    ->where('id_usuario = ?', $id)
                    ->fetchOne();
    }//

//Funciones del Login

    //logIn hago hago la busqueda si el usuario esta activo es que lo ha encontrado y por lo tanto
    //existe y devuelve login ok si no existe.

    public static function logIn($login, $password) 
    {
        $usuario = UsuarioTable::getInstance()->createQuery('u')
                ->where('u.nombre = ?', $login)
                ->andWhere('u.password = ?', $password)
                ->andWhere('u.esta_activo = 1')
                ->fetchOne();

        return $usuario;
    }//end login

    public static function logOut()
    {
    }
}//end UsuarioTable