# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: portada , action: index }

listado_articulos:
 url:   /articulos
 param: { module: articulos, action: index }
# generic rules
# please, remove them by adding more specific rules


#creo los routing del login#
login:
  url: /area-de-usuario/inicio-de-sesion
  param: { module: login, action: login }

logout:
  url:   /logout
  param: { module: login, action: logout }

area_usuario:
  url: /area-de-usuario
  param: { module: usuarios, action: conectado}

default:
  url:   /:module/:action/*
