<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/06/08 19:59:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=yodono',
  'username' => 'yodono',
  'password' => 'yodono',
  'name' => 'doctrine',
)),);
